---
kind: pipeline
type: docker
name: build

steps:
  - name: docker
    image: docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build . -t latest

  - name: build and test
    image: modelscriptci
    volumes:
      - name: cache
        path: /drone/src/target
    commands:
      - cargo clippy -- -Dwarnings
      - cargo build
      - cargo test

  - template: github-mirror
    repo: git@github.com:DSchroer/model-script.git

volumes:
  - name: cache
    host:
      path: /tmp/drone/cache/target
  - name: dockersock
    host:
      path: /var/run/docker.sock