---
kind: pipeline
type: docker
name: build

steps:
  - name: build image
    image: docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build . -t modelscriptci

#  - name: build and test
#    image: modelscriptci
#    pull: never
#    commands:
#      - cargo +nightly fmt --check
#      - cargo clippy -- -Dwarnings
#      - cargo test

  - name: build releases
    image: modelscriptci
    pull: never
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - ./scripts/use-env.sh ci
      - ./scripts/release.sh
#    when:
#      event:
#        - tag

  - name: build docs
    image: minidocks/mkdocs
    environment:
      DOCS_TOKEN:
        from_secret: drone_docs
    commands:
      - apk add git
      - git config user.name "Drone"
      - git config user.email "dominick@schroer.ca"
      - git remote add docs http://dschroer:$${DOCS_TOKEN}@gitea.swhome.ca/dschroer/model-script.git
      - mkdocs build
      - ghp-import site -p -b gh-pages -r docs --force
    when:
      event:
        - tag

  - template: github-mirror
    repo: git@github.com:DSchroer/dslcad.git

  - name: publish release
    image: maniator/gh
    environment:
      GITHUB_TOKEN:
        from_secret: github_api_key
    commands:
      - git remote add github https://github.com/DSchroer/dslcad.git
      - gh release create --prerelease $DRONE_TAG cheatsheet.md examples.zip linux.zip windows.zip macosx.zip browser.zip
    when:
      event:
        - tag

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock