---
kind: pipeline
type: docker
name: build

steps:
  - name: build and test
    image: rust
    commands:
      - apt update; apt install -y cmake libasound2-dev
      - cargo build
      - cargo test

  - template: github-mirror
    repo: git@github.com:DSchroer/model-script.git
