---
kind: pipeline
type: docker
name: build

steps:
  - name: build and test
    image: modelscriptci
    volumes:
      - name: cache
        path: /drone/src/target
    commands:
      - apt update; apt install -y cmake libasound2-dev libudev-dev libatk1.0-dev libgtk-3-dev
      - rustup component add clippy
      - cargo clippy -- -Dwarnings
      - cargo build
      - cargo test

  - template: github-mirror
    repo: git@github.com:DSchroer/model-script.git

volumes:
  - name: cache
    host:
      path: /tmp/drone/cache/target
