---
kind: pipeline
type: docker
name: build

steps:
  - name: build and test
    image: ubuntu:jammy
    commands:
      - apt update; \
        apt install -y cmake rustup
      - rustup toolchain install stable-x86_64-unknown-linux-gnu
      - rustup toolchain install stable-x86_64-pc-windows-gnu
      - cargo build
      - cargo test

  - template: github-mirror
    repo: git@github.com:DSchroer/model-script.git
