---
kind: pipeline
type: docker
name: build

steps:
  - name: build
    image: rust
    commands:
      - cargo build

  - name: test
    image: rust
    commands:
      - cargo test

  - template: github-mirror
    repo: git@github.com:DSchroer/model-script.git
