---
kind: pipeline
type: docker
name: build

steps:
  - name: build and test
    image: modelscriptci
    pull: never
    volumes:
      - name: cache
        path: /drone/src/target
    commands:
      - cargo +nightly fmt --check
      - cargo clippy -- -Dwarnings
      - cargo build
      - cargo test

  - template: github-mirror
    repo: git@github.com:DSchroer/model-script.git

volumes:
  - name: cache
    host:
      path: /tmp/drone/cache/target
