---
kind: pipeline
type: docker
name: build

steps:
  - name: build image
    image: docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build . -t modelscriptci

  - name: build and test
    image: modelscriptci
    pull: never
    volumes:
      - name: cache
        path: /drone/src/target
    commands:
      - cargo +nightly fmt --check
      - cargo clippy -- -Dwarnings
      - cargo test

  - name: build releases
    image: modelscriptci
    pull: never
    volumes:
      - name: cache
        path: /drone/src/target
    commands:
      - cargo build --release
      - cargo build --release --target x86_64-pc-windows-gnu
    when:
      event:
        - tag

  - template: github-mirror
    repo: git@github.com:DSchroer/model-script.git

volumes:
  - name: cache
    host:
      path: /tmp/drone/cache/target
  - name: dockersock
    host:
      path: /var/run/docker.sock