---
kind: pipeline
type: docker
name: build

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: modelscriptci
      tags: latest
      cache_from: modelscriptci:latest

  - name: build and test
    image: modelscriptci
    commands:
      - cargo clippy -- -Dwarnings
      - cargo build
      - cargo test

  - template: github-mirror
    repo: git@github.com:DSchroer/model-script.git
