[package]
name = "preview"
version = "0.1.0"
edition = "2021"

[dependencies]
strum = "0.24"
strum_macros = "0.24"
bevy = "0.10"
bevy_egui = "0.20.0"
smooth-bevy-cameras = "0.8.0"
bevy_polyline = "0.6.0"
bevy_points = "0.2"
persistence = { path = "../persistence" }
