[package]
name = "dslcad_app"
version = "0.1.0"
edition = "2021"
default-run = "dslcad"

[[bin]]
name = "dslcad"
path = "src/main.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1", features = ["derive"] }
bevy = "0.9.0"
bevy_egui = "0.17.1"
smooth-bevy-cameras = "0.6.0"
path-absolutize = "3.0.14"
rfd = "0.10.0"
dslcad = { path = "../dslcad" }
stl_io = "0.7.0"
notify = "5.0.0-pre.15"
bevy_polyline = "0.4.0"
bevy_points = "0.1.1"
