var width = 10;
var length = 10;
var height = 5;

var leg = cube(x=2, y=2, z=height);
var base = cube(x=width, y=length, z=1);

base
    -> union(right=leg)
    -> union(right=leg -> translate(x=0, y=width-2))
    -> union(right=leg -> translate(x=length-2, y=width-2))
    -> union(right=leg -> translate(x=length-2, y=0))
    -> rotate(x=180)
    -> translate(x=-length/2, y=width/2, z=height)
    -> fillet(radius=0.4)
    ;
