var radius = 3;
var height = 4;

var groove = face(parts=[
	point(y=radius,x=height),
	point(y=radius,x=height + 1.25),
	point(y=radius-1,x=height)
]) -> revolve(x=360)
	-> rotate(y=-90);

cylinder(radius=radius, height=2)
	-> translate(x=-radius, y=-radius, z=height)
	-> fillet(radius=0.75)
	-> difference(right=groove)
	-> union(
		right=cylinder(radius=radius, height=height)
			-> translate(x=-radius, y=-radius)
	)
	;
