[package]
name = "dslcad"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cheat_sheet"
path = "utils/cheat_sheet.rs"

[[bin]]
name = "dslcad_wasm_server"
path = "utils/dslcad_wasm_server.rs"

[dependencies]
logos = "0.12"
thiserror = "1.0.38"
path-absolutize = "3"
opencascade = { path = "../opencascade" }
dslcad_api = { path = "../dslcad_api" }
indexmap = "1.9.2"
stl_io = "0.7.0"
