name: Generate Release Artifacts

on:
  release:
    types: [ created ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  vscode:
    name: VSCode Extension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 23
          registry-url: https://registry.npmjs.org/
      - run: npm i -g vsce
      - run: just build-vscode-extension
      - uses: actions/upload-artifact@v4
        with:
          name: dslcad.vsix
          path: ./dslcad.vsix

  examples:
    name: Examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - run: just build-examples
      - uses: actions/upload-artifact@v4
        with:
          name: examples
          path: ./examples/**/*

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: extractions/setup-just@v2
      - uses: mymindstorm/setup-emsdk@v14
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - run: rustup update stable && rustup default stable && rustup target add wasm32-unknown-emscripten && rustup target add wasm32-unknown-unknown
      - run: cargo install -f wasm-bindgen-cli@0.2.89
      - run: just build-docs-editor
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force

  pack_release:
    name: Build
    continue-on-error: true
    strategy:
      matrix:
        include:
          - os: "ubuntu-latest"
            target: "x86_64-unknown-linux-gnu"
          - os: "macos-13"
            target: "x86_64-apple-darwin"
          - os: "macos-latest"
            target: "aarch64-apple-darwin"
          - os: "windows-latest"
            target: "x86_64-pc-windows-msvc"
          - os: "ubuntu-latest"
            target: "wasm32-unknown-emscripten"
          - os: "ubuntu-latest"
            target: "wasm32-unknown-unknown"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: extractions/setup-just@v2
      - if: ${{ matrix.target == 'wasm32-unknown-emscripten' }}
        uses: mymindstorm/setup-emsdk@v14
      - run: rustup update stable && rustup default stable && rustup target add ${{ matrix.target }}
      - if: ${{ matrix.target == 'wasm32-unknown-unknown' }}
        run: cargo install -f wasm-bindgen-cli@0.2.89
      - run: just CMAKE_BUILD_PARALLEL_LEVEL=4 TARGET=${{ matrix.target }} pack
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: ./target/${{ matrix.target }}/release/dslcad*
